#!/usr/bin/env python3

# Learning about the random library

"""

Neste programa o usuário tentará advinhar um número aleatório
Ex:

input: 4

Se o valor aleatório for 4, a função será encerrada. Senão, solicitará ao usuário um novo número.

"""

import random

def guess(x):
    random_number = random.randint(1,x)
    guesser = x/2
    guess = 0
    loop_count = 0
    print(f"Guesser will guess a number between 1 and {x}: \n")
    while guess != random_number:
        loop_count += 1
        guess = guesser
        print(f"The number is {guess}")
        if guess < random_number:
            print("Sorry, Guesser. Guess again. Too low.")
            guesser = int((x-guess)/2)
            guess = guesser
            print(f"Guesser will guess a number between 1 and {guess}: \n")
            print(f"His new guess is {guess}")
        elif guess > random_number:
            print("Sorry, guess again. Too hight.")
            guesser = int(guess/2)
            guess = guesser
            print(f"Guesser will guess a number between 1 and {guess}: \n")
            print(f"His new guess is {guess}")
			
    print(f"Yay, congrats. You have guessed the number {random_number} correctly!! You've tried {loop_count} times.")

x = int(input("1 and: "))
guess(x)
